# Generated by Django 2.2.6 on 2019-10-08 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, default=None, max_length=280, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_size', models.IntegerField()),
                ('image_url', models.CharField(blank=True, default=None, max_length=600, null=True)),
                ('text', models.CharField(blank=True, default=None, max_length=280, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.Camera')),
            ],
        ),
    ]
